CREATE TABLE IF NOT EXISTS `map_projects` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nombre` VARCHAR(180) NOT NULL,
  `estado` VARCHAR(40) NOT NULL DEFAULT 'Planificación',
  `etapa` VARCHAR(60) NOT NULL DEFAULT 'Diseño',
  `sector` VARCHAR(120) DEFAULT NULL,
  `monto` VARCHAR(80) DEFAULT NULL,
  `financiamiento` VARCHAR(160) DEFAULT NULL,
  `inicio` VARCHAR(80) DEFAULT NULL,
  `entrega` VARCHAR(80) DEFAULT NULL,
  `foto` TEXT DEFAULT NULL,
  `descripcion` TEXT DEFAULT NULL,
  `avance` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `lat` DECIMAL(10,7) NOT NULL,
  `lng` DECIMAL(10,7) NOT NULL,
  `visible` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
